IN:
  PREPROD:
    STORYBOARD:
    DESIGN:
    SCENARIO:
    REFS:
  FILMING:
    CONFO:
      EXR:
      PROXY:
    DOCS:
    PHOTOS:
      HDRI:
      MAKING_OF:
    RUSH:
      DAY1:
      DAY2:
      DAY3:
      DAY4:
      DAY5:
DATA:
  FILM:
    EDITING:
      VERSION:
      PUBLISH:
  LIB:
    PUBLISH:
      SET:
      FX:
      CHARA:
      PROPS:
    SET:
    FX:
    CHARA:
    PROPS:
OUT:
  EDITING:
    VERSION:
    PUBLISH:
  DAILIES:
  COMMUNICATION:
    PACKAGE_1:
    PACKAGE_2:
    PACKAGE_3:
    PACKAGE_4:
    PACKAGE_5:
TMP: