IN:
  PREPROD:
    STORYBOARD:
    DESIGN:
    SCENARIO:
    REFS:
  TOURNAGE:
    CONFO:
      EXR:
      PROXY:
    DOCS:
    PHOTOS:
      HDRI:
      MAKING_OF:
    RUSH:
      DAY1:
      DAY2:
      DAY3:
      DAY4:
      DAY5:
MONTAGE:
  CHUTIER:
    AUDIO:
    VIDEO:
  RESOLVE:
  REFS:
  EXPORT:
    AUDIO:
    VIDEO:
DATA:
  FILMS:
  LIB:
    PUBLISH:
      SET:
      FX:
      CHARA:
      PROPS:
    SET:
    FX:
    CHARA:
    PROPS:
OUT:
  RENDER:
    FILMS:
  COMPO:
    FILMS:
  MONTAGE:
    EXPORTS:
      OLD:
  DAILIES:
  COMMUNICATION:
    PACKAGE_1:
    PACKAGE_2:
    PACKAGE_3:
    PACKAGE_4:
    PACKAGE_5:
TMP: