IN:
  PREPROD:
    STORYBOARD:
    DESIGN:
    SCENARIO:
    REFS:
  TOURNAGE:
    CONFO:
      EXR:
      PROXY:
    DOCS:
    PHOTOS:
      HDRI:
      MAKING_OF:
    RUSH:
      DAY1:
      DAY2:
      DAY3:
      DAY4:
      DAY5:
MONTAGE:
  CHUTIER:
    AUDIO:
    VIDEO:
  RESOLVE:
  REFS:
  EXPORT:
    AUDIO:
    VIDEO:
DATA:
  FILMS:
  LIB:
    PUBLISH:
      SET:
        ASSEMBLAGE:
          HD:
            OLD:
          LD:
            OLD:
        MODULES:
          HD:
          LD:
          TEXTURES:
            HD:
            LD:
      FX:
      CHARA:
      PROPS:
    SET:
    FX:
    CHARA:
    PROPS:
OUT:
  RENDER:
    FILMS:
  COMPO:
    FILMS:
  MONTAGE:
    EXPORTS:
      OLD:
  DAILIES:
  COMMUNICATION:
    PACKAKE_1:
    PACKAKE_2:
    PACKAKE_3:
    PACKAKE_4:
    PACKAKE_5:
TMP: