designer:
  cwd: C:\Program Files\Allegorithmic\Substance Designer
  exe: C:\Program Files\Allegorithmic\Substance Designer\Substance Designer.exe
guerilla:
  cwd: C:\Program Files\Guerilla Render
  exe: C:\Program Files\Guerilla Render\guerilla.exe
houdini:
  cwd: C:\Program Files\Side Effects Software\Houdini 18.5.563
  exe: C:\Program Files\Side Effects Software\Houdini 18.5.563\bin\houdini.exe
mari:
  cwd: C:\Program Files\Mari4.7v2
  exe: C:\Program Files\Mari4.7v2\Bundle\bin\Mari4.7v2.exe
maya:
  cwd: C:\Program Files\Autodesk\Maya2020
  exe: C:\Program Files\Autodesk\Maya2020\bin\maya.exe
nuke:
  cwd: C:\Program Files\Nuke13.0v2
  exe: C:\Program Files\Nuke13.0v2\Nuke13.0.exe
painter:
  cwd: C:\Program Files\Allegorithmic\Substance Painter
  exe: C:\Program Files\Allegorithmic\Substance Painter\Substance Painter.exe
photoshop:
  cwd: C:\Program Files\Adobe\Adobe Photoshop 2021
  exe: C:\Program Files\Adobe\Adobe Photoshop 2021\Photoshop.exe
resolve:
  cwd: C:\Program Files\Blackmagic Design\DaVinci Resolve
  exe: C:\Program Files\Blackmagic Design\DaVinci Resolve\Resolve.exe
zbrush:
  cwd: C:\Program Files\Pixologic\ZBrush 2021
  exe: C:\Program Files\Pixologic\ZBrush 2021\ZBrush.exe
